### ISSUE TITLE
is the plugin support vulkan?

### ISSUE THREAD

**Issue by anningning** [UNAmedia/ue4-stereo-panoramic-player-demo#2]
when i pack with vulkan, the fps 10.....

**Comment by kafumanto** [comment]
Following email support:

All rendering system of Unreal Engine are supported, including Vulkan. But the Vulkan implementation in UE4.27 is much slower than the OpenGL one. Several users switched to OpenGL (and the Electra player module) to playback 4k 360 stereo videos on Quest 2 and Pico, for performance reasons. More [details in our Discord server](https://discord.com/channels/898503629655408660/898527847872884777/1242125536692539547).
